### ISSUE TITLE
to clean "fish: Unknown command: __to_expand" deletes all bookmarks

### ISSUE THREAD

**Issue by et-rnal** [joehillen/to-fish#11]
on a fresh install of fish shell, the "clean" function appears to not be functional. the resulting behavior is deletion of all bookmarks. this occurs regardless as to whether or not any symlinks are broken 

```
$ to ls
here -> ~/.config/fish/functions

$ to clean
fish: Unknown command: __to_expand
in command substitution
	called on line 203 of file ~/.config/fish/functions/to.fish
in function 'to' with arguments 'clean'
~/.config/fish/functions/to.fish (line 203): Unknown command
        set -l dest (__to_expand $bm)
                    ^~~~~~~~~~~~~~~~^
in function 'to' with arguments 'clean'
removed '/home/user/.config/fish/bookmarks/here'

```

**Comment by joehillen** [comment]
I'm super sorry that your bookmarks were deleted. It should be resolved now.

FYI: I changed the default bookmarks dir to `~/.local/share/to-fish`
