### ISSUE TITLE
Fish bookmark entire list of folder in a directory

### ISSUE THREAD

**Issue by bekicot** [joehillen/to-fish#7]
Just like a path for bins, but it is a path for bookmarks.

use case:

I have a directory called GitHub that contains a list of open-source projects.

```sh
$ ls github
administrate
direnv
rails
...
```

I add github to fish path list
```sh
to path add ~/GitHub
```

Whenever I want to go to rails I can do:
```
to rails
```

What do you think?

**Comment by joehillen** [comment]
You can do this by with a for loop. `for d in /foo/bar/*/; to add $d; end`

I had a desire for similar functionality and I tried to enable it by improving the completions. If you add a slash after the bookmark it will complete the subdirectories. It's not perfect, but it kind of works
